### ISSUE TITLE
Fullres/50mpx conversion FC

### ISSUE THREAD

**Issue by pjgoncalves72** [amirzaidi/DNGProcessor#14]
While trying to convert 50mpx/full resolution dng to jpg the app force closes.

12mpx dngs converts perfectly.

Running on xiaomi.eu latest weekly on Xiaomi 13 Ultra device.

**Comment by pjgoncalves72** [comment]
Device with 16Gb ram 


java.lang.OutOfMemoryError: Failed to allocate a 100663315 byte allocation with 69207216 free bytes and 66MB until OOM, target footprint 536870912, growth limit 536870912
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:70)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:260)
	at amirz.dngprocessor.gl.Texture.setPixels(Texture.java:79)
	at amirz.dngprocessor.pipeline.convert.PreProcess.execute(PreProcess.java:56)
	at amirz.dngprocessor.pipeline.StagePipeline.execute(StagePipeline.java:104)
	at amirz.dngprocessor.parser.DngParser.run(DngParser.java:232)
	at amirz.dngprocessor.scheduler.DngParseService.onHandleIntent(DngParseService.java:61)
	at android.app.IntentService$ServiceHandler.handleMessage(Unknown Source:6)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.os.HandlerThread.run(Unknown Source:28)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void amirz.dngprocessor.gl.Texture.close()' on a null object reference
		at amirz.dngprocessor.pipeline.intermediate.MergeDetail.close(MergeDetail.java:90)
		at amirz.dngprocessor.pipeline.StagePipeline.close(StagePipeline.java:117)
		at amirz.dngprocessor.parser.DngParser.run(DngParser.java:230)
		... 6 more
